version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.Golang
    container_name: backend
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "8080:8080"
    env_file: .env
    restart: unless-stopped
    networks:
      - backend_network

networks:
  backend_network:
    external: true